Implemented prioritizing goals
Marouann/IAMAS_project pull request #28
Opened 2019-04-27 14:05 UTC by JacekPelic

2019-04-27 16:18 UTC, Marouann requested changes

2019-04-27 16:18 UTC, Marouann commented on client/masterAgent.py
> +        sortedGoals = self.priorytazeGoals(goalsToAssign)
prioritizeGoals maybe

2019-04-27 16:18 UTC, Marouann commented on client/masterAgent.py
> +    def priorytazeGoals(self, goals):
same prioritizeGoals

2019-04-27 16:18 UTC, Marouann commented
Nice job, it's working very fine on SALazarus

2019-04-28 14:54 UTC, Marouann reviewed
One thing that might be improved (later, not the priority right now) is to compute these prioritization at the initialization. Right now you are only using rigid_atoms so we could compute it once for all.

2019-04-28 14:54 UTC, Marouann commented on client/state.py
> +        for atom in self.rigid_atoms:
You are using two times the same 3 line of codes. You could create a method getNeighbourLocations into the class state

2019-04-30 06:25 UTC, pierlj approved these changes

2019-04-30 11:18 UTC, merged